# Q3 Using Scikit-Learn

In [2]:
import numpy as np
import pandas as pd
import time
import gc

from sklearn.model_selection import cross_val_score, GridSearchCV, cross_validate, train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.decomposition import PCA
# Import statements run before running other code cells

# Classifier Setup

In [3]:
# XXX
# TODO: Read in all the data. Replace the 'xxx' with the path to the data set.
# XXX

# data = pd.read_csv('xxx')

# Separate out the x_data and y_data.
# x_data = data.loc[:, data.columns != "y"]
# y_data = data.loc[:, "y"]

# -------------------------------
# ADD CODE HERE
data = pd.read_csv('pulsar_stars.csv')

x_data = data.loc[:, data.columns != "y"]
y_data = data.loc[:, "y"]

# -------------------------------

In [5]:
# The random state to use while splitting the data.
random_state = 100

# XXX
# TODO: Split 70% of the data into training and 30% into test sets. Call them x_train, x_test, y_train and y_test.
# Use the train_test_split method in sklearn with the parameter 'shuffle' set to true and the 'random_state' set to 100.
# XXX

# -------------------------------
# ADD CODE HERE
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3, random_state= random_state, shuffle = True)

# -------------------------------

# Linear Regression 

In [6]:
# XXX
# TODO: Create a LinearRegression classifier and train it.
# XXX

# -------------------------------
# ADD CODE HERE
lr_model = LinearRegression().fit(x_train,y_train)
lr_pred_train=lr_model.predict(x_train)
lr_pred_test=lr_model.predict(x_test)

# -------------------------------



In [7]:
# XXX
# TODO: Test its accuracy (on the training set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
# ADD CODE HERE
vfunc = np.vectorize(lambda x: 1 if x>=0.5 else 0)
lr_pred_train=vfunc(lr_pred_train)


accuracy_train=accuracy_score(y_train,lr_pred_train,normalize=True)
print(accuracy_train)

# -------------------------------

0.970705619412516


In [8]:
# XXX
# TODO: Test its accuracy (on the testing set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
# ADD CODE HERE
vfunc = np.vectorize(lambda x: 1 if x>=0.5 else 0)
lr_pred_test=vfunc(lr_pred_test)
accuracy_test=accuracy_score(y_test,lr_pred_test)


print(accuracy_test)

# -------------------------------

0.9720670391061452


# Random Forest Classifier

In [9]:
# XXX
# TODO: Create a RandomForestClassifier and train it.
# WARNING: Ignore "FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22."10 in version 0.20 to 100 in 0.22."
# XXX

# -------------------------------
# ADD CODE HERE
rand_for= RandomForestClassifier(n_estimators=100,random_state=random_state)
rand_for.fit(x_train,y_train)

rand_pred_train=rand_for.predict(x_train)
rand_pred_test=rand_for.predict(x_test)

# -------------------------------

In [10]:
# XXX
# TODO: Test its accuracy on the training set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
vfunc = np.vectorize(lambda x: 1 if x>=0.5 else 0)
rand_pred_train=vfunc(rand_pred_train)


accuracy_train_r=accuracy_score(y_train,rand_pred_train,normalize=True)
print(accuracy_train_r)

# -------------------------------


1.0


In [11]:
# XXX
# TODO: Test its accuracy on the test set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
rand_pred_test=vfunc(rand_pred_test)
accuracy_test_r=accuracy_score(y_test,rand_pred_test)


print(accuracy_test_r)

# -------------------------------


0.9817504655493482


## Feature Importance

In [12]:
# XXX
# TODO: Determine and print the feature importance as evaluated by the Random Forest Classifier.
# XXX

# -------------------------------
# ADD CODE HERE
x=rand_for.feature_importances_
print(x)

# -------------------------------

[0.1809442  0.0491881  0.33429017 0.21197966 0.05940259 0.06157055
 0.05285945 0.04976529]


In [13]:
# XXX
# TODO: Sort them in the descending order and print the feature numbers[0 to ...].
#       Hint: There is a direct function available in sklearn to achieve this. Also checkout argsort() function in Python.
# XXX

# -------------------------------
# ADD CODE HERE
print(x.argsort()[::-1])

# -------------------------------

[2 3 0 5 4 6 7 1]


## Hyper-parameter Tuning

In [14]:
# XXX
# TODO: Tune the hyper-parameters 'n_estimators' and 'max_depth'.
# XXX

# -------------------------------
# ADD CODE HERE
n_esti = [80,85,90,95,100]
max_d=[6,7,8,9,10,11,12]


param_grid = dict(n_estimators=n_esti,
                  max_depth=max_d)

grid = GridSearchCV(estimator=RandomForestClassifier(random_state=100),
                    param_grid=param_grid,
                    scoring='roc_auc',cv = 10,n_jobs=5)
grid_result = grid.fit(x_train, y_train)


# -------------------------------

In [15]:
# XXX
# TODO: Print the best params, using .best_params_
# XXX

# -------------------------------
# ADD CODE HERE
print('Best Params: ', grid_result.best_params_)

# -------------------------------


Best Params:  {'max_depth': 8, 'n_estimators': 90}


In [16]:
# XXX
# TODO: Print the best score, using .best_score_.
# XXX

# -------------------------------
# ADD CODE HERE
print('Best Score: ', grid_result.best_score_)

# -------------------------------


Best Score:  0.9747116854681365


# Support Vector Machine

## Pre-process

In [17]:
# XXX
# TODO: Pre-process the data to standardize or normalize it, otherwise the grid search will take much longer.
# Warning: Ignore "FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning"
# XXX

# -------------------------------
# ADD CODE HERE
scaler = StandardScaler()
x_train_n = scaler.fit_transform(x_train)
x_test_n = scaler.fit_transform(x_test)


# -------------------------------


In [18]:
# XXX
# TODO: Create a SVC classifier and train it.
# XXX

# -------------------------------
# ADD CODE HERE
svclassifier = SVC(random_state=random_state)
svclassifier.fit(x_train_n, y_train)



# -------------------------------


In [19]:
# XXX
# TODO: Test its accuracy on the training set using the accuracy_score method.
# XXX
# WARNING: Ignore "FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.""

# -------------------------------
# ADD CODE HERE

y_train_predict_sv = svclassifier.predict(x_train_n)
y_train_predict_sv=vfunc(y_train_predict_sv)

accuracy_train_s=accuracy_score(y_train,y_train_predict_sv)
print(accuracy_train_s)

# -------------------------------


0.978448275862069


In [20]:
# XXX
# TODO: Test its accuracy on the test set using the accuracy_score method.
# XXX
# WARNING: Ignore "FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.""

# -------------------------------
# ADD CODE HERE

y_predict_sv = svclassifier.predict(x_test_n)
y_predict_sv=vfunc(y_predict_sv)

accuracy_test_s=accuracy_score(y_test,y_predict_sv)
print(accuracy_test_s)

# -------------------------------

0.9798882681564246


## Hyper-parameter Tuning

In [22]:
# XXX
# TODO: Tune the hyper-parameters 'C' and 'kernel' (use rbf and linear).
# XXX

# -------------------------------
# ADD CODE HERE

svmTunePram = {'kernel':['linear', 'rbf'], 'C':[0.01, 0.1, 1]}
svm_model2 = GridSearchCV(SVC(), svmTunePram, cv=10,n_jobs=5)
svm_model2.fit(x_train_n, y_train)
print(svm_model2.best_params_)

# -------------------------------

{'C': 1, 'kernel': 'linear'}


In [23]:
# XXX
# TODO: Print the best score, using .best_score_.
# XXX

# -------------------------------
# ADD CODE HERE
print(svm_model2.best_score_)

# -------------------------------

0.977889527458493


# Support Vector Machine

In [24]:
# XXX
# TODO: Calculate the training and test set accuracy values after hyperparameter tuning and normalization. 
# XXX

# -------------------------------
# ADD CODE HERE
y_train_predict_sv = svm_model2.predict(x_train_n)

y_predict_sv = svm_model2.predict(x_test_n)


# -------------------------------

In [25]:
# XXX
# TODO: Test its accuracy (on the training set) using the accuracy_score method. Print the result
# XXX

# -------------------------------
# ADD CODE HERE
y_train_predict_sv=vfunc(y_train_predict_sv)

accuracy_train_s=accuracy_score(y_train,y_train_predict_sv)
print(accuracy_train_s)

# -------------------------------

0.9782088122605364


In [26]:
# XXX
# TODO: Test its accuracy (on the testing set) using the accuracy_score method. Print the result
# XXX

# -------------------------------
# ADD CODE HERE
y_predict_sv=vfunc(y_predict_sv)

accuracy_test_s=accuracy_score(y_test,y_predict_sv)
print(accuracy_test_s)

# -------------------------------

0.9804469273743017


In [27]:
# XXX
# TODO: Calculate the rank test score, mean testing score and mean fit time for the 
# all hyperparameter values that you obtained in Q3.2. The GridSearchCV 
# class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
# ADD CODE HERE
print(svm_model2.cv_results_)

# -------------------------------

{'mean_fit_time': array([0.67797687, 2.40306134, 0.72724805, 1.40556223, 1.14311948,
       1.26234002]), 'std_fit_time': array([0.02456341, 0.04791068, 0.01713498, 0.02398581, 0.13888114,
       0.04370688]), 'mean_score_time': array([0.03887315, 0.17454095, 0.03570464, 0.08616748, 0.03263927,
       0.07498951]), 'std_score_time': array([0.00465463, 0.02185352, 0.00802523, 0.00934389, 0.00755116,
       0.01183345]), 'param_C': masked_array(data=[0.01, 0.01, 0.1, 0.1, 1, 1],
             mask=[False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
             mask=[False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'C': 0.01, 'kernel': 'linear'}, {'C': 0.01, 'kernel': 'rbf'}, {'C': 0.1, 'kernel': 'linear'}, {'C': 0.1, 'kernel': 'rbf'}, {'C': 1, 'kernel': 'linear'}, {'C': 1, 'kernel': 'rbf'}], 'split0_test_s

In [28]:
# XXX
# TODO: Print the rank test score for all hyperparameter values that you obtained in Q3.2. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
# ADD CODE HERE

print(svm_model2.cv_results_['rank_test_score'])

# -------------------------------

[5 6 3 4 1 2]


In [29]:
# XXX
# TODO: Print mean testing score for all of hyperparameter values that you obtained in Q3.2. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
# ADD CODE HERE

print(svm_model2.cv_results_['mean_test_score'])

# -------------------------------

[0.97413793 0.9683908  0.97717114 0.97573436 0.97788953 0.97757024]


In [30]:
# XXX
# TODO: Print mean fit time for all of hyperparameter values that you obtained in Q3.2. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
# ADD CODE HERE

print(svm_model2.cv_results_['mean_fit_time'])

# -------------------------------

[0.67797687 2.40306134 0.72724805 1.40556223 1.14311948 1.26234002]


# PCA

In [31]:
# XXX
# TODO: Perform dimensionality reduction of the data using PCA.
#       Set parameters n_component to 8 and svd_solver to 'full'. Keep other parameters at their default value.
# XXX

# -------------------------------
# ADD CODE HERE
from sklearn import decomposition as decom

x_pca = StandardScaler().fit_transform(x_train)


pca=decom.PCA(n_components=8,svd_solver='full')
principal_components=pca.fit_transform(x_train)

# -------------------------------

In [32]:
# XXX
# TODO: Print Percentage of variance explained by each of the selected components
# XXX

# -------------------------------

print(pca.explained_variance_ratio_)
# -------------------------------

[8.71054855e-01 7.80404050e-02 4.12747422e-02 6.15520409e-03
 2.45425694e-03 9.78533643e-04 3.91429289e-05 2.85984066e-06]


In [33]:
# XXX
# TODO: The singular values corresponding to each of the selected components.
# XXX

# -------------------------------

print(pca.singular_values_)
# -------------------------------

[11992.97512747  3589.74779466  2610.63625426  1008.15059028
   636.59642313   401.9685368     80.39533321    21.73076915]
